In [3]:
import pandas as pd

customer_data_file="Online Retail.xlsx"
datos= pd.read_excel(customer_data_file)
datos.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom

In [4]:
#Eliminar todos los valores que contien Nan
datos=datos.dropna()
datos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    406829 non-null  object
 1   StockCode    406829 non-null  object
 2   Description  406829 non-null  object
 3   Quantity     406829 non-null  int64
 4   InvoiceDate  406829 non-null  datetime64[ns]
 5   UnitPrice    406829 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      406829 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 27.9+ MB

In [5]:
datos_reales= datos[datos["Quantity"]>0]
datos_reales.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 397924 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397924 non-null  object
 1   StockCode    397924 non-null  object
 2   Description  397924 non-null  object
 3   Quantity     397924 non-null  int64
 4   InvoiceDate  397924 non-null  datetime64[ns]
 5   UnitPrice    397924 non-null  float64
 6   CustomerID   397924 non-null  float64
 7   Country      397924 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 27.3+ MB

In [7]:
basket = (datos_reales.groupby(["InvoiceNo","Description"]))["Quantity"].sum().unstack().reset_index().fillna(0).set_index("InvoiceNo")
basket

Description,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,I LOVE LONDON MINI RUCKSACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536366,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536367,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536368,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536369,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581583,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581584,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581585,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,12.0,0.0,0.0,0.0,24.0,0.0,0.0
581586,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581587,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
#Clasificación a binario de la base previa para identificar si un articulo se compró o no
def codificar(x):
    if x<=0:
        return 0
    if x>= 1:
        return 1
basket_codificado= basket.applymap(codificar)
basket_codificado

Description,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,I LOVE LONDON MINI RUCKSACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536366,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536367,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536368,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536369,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581583,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581584,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581585,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
581586,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581587,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
#Filtrado de transacciones donde se han comprado más de 1 articulo
basket_filtrado= basket_codificado[(basket_codificado >0).sum(axis=1) >=2]
basket_filtrado

Description,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,I LOVE LONDON MINI RUCKSACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536366,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536367,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536368,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536370,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581583,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581584,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581585,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
581586,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581587,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
#Instalación del módulo mlxtend
!pip install mlxtend

Requirement already satisfied: mlxtend in .\.conda\envs\pdi2026_ok\lib\site-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in .\.conda\envs\pdi2026_ok\lib\site-packages (from mlxtend) (1.15.3)
Requirement already satisfied: numpy>=1.16.2 in .\.conda\envs\pdi2026_ok\lib\site-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in .\.conda\envs\pdi2026_ok\lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: scikit-learn>=1.3.1 in .\.conda\envs\pdi2026_ok\lib\site-packages (from mlxtend) (1.7.2)
Requirement already satisfied: matplotlib>=3.0.0 in .\.conda\envs\pdi2026_ok\lib\site-packages (from mlxtend) (3.10.8)
Requirement already satisfied: joblib>=0.13.2 in .\.conda\envs\pdi2026_ok\lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in .\.conda\envs\pdi2026_ok\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: cycler>=0.10 in .\.conda\envs\pdi2026_ok\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\.conda\envs\pdi2026_ok\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in .\.conda\envs\pdi2026_ok\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in .\.conda\envs\pdi2026_ok\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (25.0)
Requirement already satisfied: pillow>=8 in .\.conda\envs\pdi2026_ok\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (12.1.1)
Requirement already satisfied: pyparsing>=3 in .\.conda\envs\pdi2026_ok\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in .\.conda\envs\pdi2026_ok\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\.conda\envs\pdi2026_ok\lib\site-packages (from pandas>=0.24.2->mlxtend) (2026.1.post1)
Requirement already satisfied: six>=1.5 in .\.conda\envs\pdi2026_ok\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in .\.conda\envs\pdi2026_ok\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)

In [13]:
#Aplicación del algoritmo "a priori" para localizar los articulos frecuentemente comprados
from mlxtend.frequent_patterns import apriori

In [15]:
#Analisis "a priori" con un soporte minimo de 3
articulos_frecuentes= apriori(basket_filtrado,min_support=0.03,use_colnames=True).sort_values("support",ascending=False).reset_index(drop=True)
articulos_frecuentes["lenght"]= articulos_frecuentes["itemsets"].apply(lambda x:len(x))
articulos_frecuentes

C:\Users\Josue Santana Robled\.conda\envs\PDI2026_OK\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

      support                                           itemsets  lenght
0    0.113952               (WHITE HANGING HEART T-LIGHT HOLDER)       1
1    0.098249                         (REGENCY CAKESTAND 3 TIER)       1
2    0.092586                          (JUMBO BAG RED RETROSPOT)       1
3    0.080152                    (ASSORTED COLOUR BIRD ORNAMENT)       1
4    0.079685                                    (PARTY BUNTING)       1
..        ...                                                ...     ...
107  0.030356                    (SET OF 3 HEART COOKIE CUTTERS)       1
108  0.030239                    (RED TOADSTOOL LED NIGHT LIGHT)       1
109  0.030181  (LUNCH BAG RED RETROSPOT, LUNCH BAG  BLACK SKU...       2
110  0.030181                           (BLUE HARMONICA IN BOX )       1
111  0.030064                     (HOMEMADE JAM SCENTED CANDLES)       1

[112 rows x 3 columns]

In [16]:
from mlxtend.frequent_patterns import association_rules

In [17]:
association_rules(articulos_frecuentes, metric="confidence", min_threshold=0.5).sort_values("confidence",ascending=False).reset_index(drop=True)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(GREEN REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER ),0.040339,0.045534,0.031582,0.782923,17.194200,1.0,0.029745,4.396906,0.981430,0.581720,0.772567,0.738257
1,(ROSES REGENCY TEACUP AND SAUCER ),(GREEN REGENCY TEACUP AND SAUCER),0.045534,0.040339,0.031582,0.693590,17.194200,1.0,0.029745,3.131949,0.986773,0.581720,0.680710,0.738257
2,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED ),0.045768,0.051197,0.030940,0.676020,13.204367,1.0,0.028597,2.928590,0.968598,0.468612,0.658539,0.640177
3,(JUMBO BAG PINK POLKADOT),(JUMBO BAG RED RETROSPOT),0.050730,0.092586,0.031874,0.628308,6.786206,1.0,0.027177,2.441309,0.898208,0.286014,0.590384,0.486285
4,(ALARM CLOCK BAKELIKE RED ),(ALARM CLOCK BAKELIKE GREEN),0.051197,0.045768,0.030940,0.604333,13.204367,1.0,0.028597,2.411705,0.974140,0.468612,0.585356,0.640177
5,(LUNCH BAG PINK POLKADOT),(LUNCH BAG RED RETROSPOT),0.054291,0.075131,0.030531,0.562366,7.485099,1.0,0.026452,2.113336,0.916139,0.308737,0.526815,0.484368

In [18]:
association_rules(articulos_frecuentes, metric="lift", min_threshold=1.01).sort_values("lift",ascending=False).reset_index(drop=True)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(ROSES REGENCY TEACUP AND SAUCER ),(GREEN REGENCY TEACUP AND SAUCER),0.045534,0.040339,0.031582,0.693590,17.194200,1.0,0.029745,3.131949,0.986773,0.581720,0.680710,0.738257
1,(GREEN REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER ),0.040339,0.045534,0.031582,0.782923,17.194200,1.0,0.029745,4.396906,0.981430,0.581720,0.772567,0.738257
2,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED ),0.045768,0.051197,0.030940,0.676020,13.204367,1.0,0.028597,2.928590,0.968598,0.468612,0.658539,0.640177
3,(ALARM CLOCK BAKELIKE RED ),(ALARM CLOCK BAKELIKE GREEN),0.051197,0.045768,0.030940,0.604333,13.204367,1.0,0.028597,2.411705,0.974140,0.468612,0.585356,0.640177
4,(LUNCH BAG PINK POLKADOT),(LUNCH BAG RED RETROSPOT),0.054291,0.075131,0.030531,0.562366,7.485099,1.0,0.026452,2.113336,0.916139,0.308737,0.526815,0.484368
5,(LUNCH BAG RED RETROSPOT),(LUNCH BAG PINK POLKADOT),0.075131,0.054291,0.030531,0.406371,7.485099,1.0,0.026452,1.593099,0.936783,0.308737,0.372293,0.484368
6,(JUMBO BAG PINK POLKADOT),(JUMBO BAG RED RETROSPOT),0.050730,0.092586,0.031874,0.628308,6.786206,1.0,0.027177,2.441309,0.898208,0.286014,0.590384,0.486285
7,(JUMBO BAG RED RETROSPOT),(JUMBO BAG PINK POLKADOT),0.092586,0.050730,0.031874,0.344262,6.786206,1.0,0.027177,1.447637,0.939640,0.286014,0.309219,0.486285
8,(LUNCH BAG RED RETROSPOT),(LUNCH BAG BLACK SKULL.),0.075131,0.061296,0.030181,0.401709,6.553602,1.0,0.025576,1.568977,0.916251,0.284066,0.362642,0.447045
9,(LUNCH BAG BLACK SKULL.),(LUNCH BAG RED RETROSPOT),0.061296,0.075131,0.030181,0.492381,6.553602,1.0,0.025576,1.821974,0.902747,0.284066,0.451145,0.447045