In [31]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [32]:
df = pd.read_csv('kc_house_data.csv')
print(df.shape)
df.head()

(21613, 21)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [33]:
Y = df['price'].values.reshape(-1, 1)
Y

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [402101.],
       [400000.],
       [325000.]], shape=(21613, 1))

In [34]:
X_data = df.drop(columns=['id', 'date', 'zipcode', 'price',
                          'sqft_above', 'sqft_basement'])

# Agregar columna de 1's (intercepto)
unos = np.ones((X_data.shape[0], 1))
X = np.hstack([unos, X_data.values])

# Nombres de las columnas
nombres = ['const'] + X_data.columns.tolist()

print("Dimensiones X:", X.shape)
print("Nombres:", nombres)
X

Dimensiones X: (21613, 16)
Nombres: ['const', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade', 'yr_built', 'yr_renovated', 'lat', 'long', 'sqft_living15', 'sqft_lot15']

array([[ 1.00000e+00,  3.00000e+00,  1.00000e+00, ..., -1.22257e+02,
         1.34000e+03,  5.65000e+03],
       [ 1.00000e+00,  3.00000e+00,  2.25000e+00, ..., -1.22319e+02,
         1.69000e+03,  7.63900e+03],
       [ 1.00000e+00,  2.00000e+00,  1.00000e+00, ..., -1.22233e+02,
         2.72000e+03,  8.06200e+03],
       ...,
       [ 1.00000e+00,  2.00000e+00,  7.50000e-01, ..., -1.22299e+02,
         1.02000e+03,  2.00700e+03],
       [ 1.00000e+00,  3.00000e+00,  2.50000e+00, ..., -1.22069e+02,
         1.41000e+03,  1.28700e+03],
       [ 1.00000e+00,  2.00000e+00,  7.50000e-01, ..., -1.22299e+02,
         1.02000e+03,  1.35700e+03]], shape=(21613, 16))

In [35]:
XT_X = np.matmul(np.matrix.transpose(X), X)
XT_X

array([[ 2.16130000e+04,  7.28540000e+04,  4.57062500e+04,
         4.49528730e+07,  3.26506890e+08,  3.22965000e+04,
         1.63000000e+02,  5.06400000e+03,  7.36880000e+04,
         1.65488000e+05,  4.25993340e+07,  1.82418600e+06,
         1.02791542e+06, -2.64140894e+06,  4.29353590e+07,
         2.75964632e+08],
       [ 7.28540000e+04,  2.64274000e+05,  1.62054750e+05,
         1.62175001e+08,  1.12699827e+09,  1.10770500e+05,
         5.38000000e+02,  1.82950000e+04,  2.48763000e+05,
         5.66268000e+05,  1.43686638e+08,  6.30116200e+06,
         3.46491519e+06, -8.90340471e+06,  1.50123770e+08,
         9.46283104e+08],
       [ 4.57062500e+04,  1.62054750e+05,  1.09476812e+05,
         1.06601162e+08,  7.50973606e+08,  7.27991250e+04,
         4.36500000e+02,  1.31037500e+04,  1.54478500e+05,
         3.62977500e+05,  9.03346532e+07,  4.19694425e+06,
         2.17384832e+06, -5.58541608e+06,  9.72849460e+07,
         6.23216959e+08],
       [ 4.49528730e+07,  1.62175001e+08,  1.06601162e+08,
         1.11727919e+11,  8.21193670e+11,  7.09672610e+07,
         5.17311000e+05,  1.48618050e+07,  1.52504755e+08,
         3.61993934e+08,  8.87877796e+10,  4.23553645e+09,
         2.13810548e+09, -5.49319426e+09,  9.95920129e+10,
         6.73314049e+11],
       [ 3.26506890e+08,  1.12699827e+09,  7.50973606e+08,
         8.21193670e+11,  4.20113464e+13,  4.85388085e+08,
         4.13560800e+06,  1.27752236e+08,  1.10798376e+09,
         2.61957937e+09,  6.44942478e+11,  3.03063340e+10,
         1.55180568e+10, -3.98747443e+10,  7.37347226e+11,
         2.17320665e+13],
       [ 3.22965000e+04,  1.10770500e+05,  7.27991250e+04,
         7.09672610e+07,  4.85388085e+08,  5.45627500e+04,
         2.67500000e+02,  7.83050000e+03,  1.08109500e+05,
         2.53575500e+05,  6.38243035e+07,  2.75561000e+06,
         1.53610347e+06, -3.94687498e+06,  6.63974055e+07,
         4.08785543e+08],
       [ 1.63000000e+02,  5.38000000e+02,  4.36500000e+02,
         5.17311000e+05,  4.13560800e+06,  2.67500000e+02,
         1.63000000e+02,  6.14000000e+02,  5.76000000e+02,
         1.43000000e+03,  3.19837000e+05,  8.35200000e+04,
         7.74859040e+03, -1.99319010e+04,  4.34615000e+05,
         3.64877200e+06],
       [ 5.06400000e+03,  1.82950000e+04,  1.31037500e+04,
         1.48618050e+07,  1.27752236e+08,  7.83050000e+03,
         6.14000000e+02,  1.38780000e+04,  1.77610000e+04,
         4.36670000e+04,  9.95517300e+06,  1.11872000e+06,
         2.40858235e+05, -6.19074027e+05,  1.32432260e+07,
         9.74778540e+07],
       [ 7.36880000e+04,  2.48763000e+05,  1.54478500e+05,
         1.52504755e+08,  1.10798376e+09,  1.08109500e+05,
         5.76000000e+02,  1.77610000e+04,  2.60386000e+05,
         5.61828000e+05,  1.45090124e+08,  5.87699400e+06,
         3.50457603e+06, -9.00590853e+06,  1.45490324e+08,
         9.39574232e+08],
       [ 1.65488000e+05,  5.66268000e+05,  3.62977500e+05,
         3.61993934e+08,  2.61957937e+09,  2.53575500e+05,
         1.43000000e+03,  4.36670000e+04,  5.61828000e+05,
         1.29698200e+06,  3.26511223e+08,  1.41146480e+07,
         7.87101956e+06, -2.02242236e+07,  3.41168653e+08,
         2.19574080e+09],
       [ 4.25993340e+07,  1.43686638e+08,  9.03346532e+07,
         8.87877796e+10,  6.44942478e+11,  6.38243035e+07,
         3.19837000e+05,  9.95517300e+06,  1.45090124e+08,
         3.26511223e+08,  8.39821529e+10,  3.53813874e+09,
         2.02601353e+09, -5.20619400e+09,  8.47677549e+10,
         5.45157634e+11],
       [ 1.82418600e+06,  6.30116200e+06,  4.19694425e+06,
         4.23553645e+09,  3.03063340e+10,  2.75561000e+06,
         8.35200000e+04,  1.11872000e+06,  5.87699400e+06,
         1.41146480e+07,  3.53813874e+09,  3.64097975e+09,
         8.67937439e+07, -2.23024467e+08,  3.60793969e+09,
         2.51536167e+10],
       [ 1.02791542e+06,  3.46491519e+06,  2.17384832e+06,
         2.13810548e+09,  1.55180568e+10,  1.53610347e+06,
         7.74859040e+03,  2.40858235e+05,  3.50457603e+06,
         7.87101956e+06,  2.02601353e+09,  8.67937439e+07,
         4.88881261e+07, -1.25625605e+08,  2.04210821e+09,
         1.31178263e+10],
       [-2.64140894e+06, -8.90340471e+06, -5.58541608e+06,
        -5.49319426e+09, -3.98747443e+10, -3.94687498e+06,
        -1.99319010e+04, -6.19074027e+05, -9.00590853e+06,
        -2.02242236e+07, -5.20619400e+09, -2.23024467e+08,
        -1.25625605e+08,  3.22817308e+08, -5.24659952e+09,
        -3.37055674e+10],
       [ 4.29353590e+07,  1.50123770e+08,  9.72849460e+07,
         9.95920129e+10,  7.37347226e+11,  6.63974055e+07,
         4.34615000e+05,  1.32432260e+07,  1.45490324e+08,
         3.41168653e+08,  8.47677549e+10,  3.60793969e+09,
         2.04210821e+09, -5.24659952e+09,  9.54458243e+10,
         6.22309762e+11],
       [ 2.75964632e+08,  9.46283104e+08,  6.23216959e+08,
         6.73314049e+11,  2.17320665e+13,  4.08785543e+08,
         3.64877200e+06,  9.74778540e+07,  9.39574232e+08,
         2.19574080e+09,  5.45157634e+11,  2.51536167e+10,
         1.31178263e+10, -3.37055674e+10,  6.22309762e+11,
         1.96357821e+13]])

In [36]:
XT_X_inv = np.linalg.inv(XT_X)
XT_X_inv

array([[ 5.88395762e+01, -2.39334627e-03,  1.07464267e-02,
        -6.18082466e-06, -1.68980105e-07,  1.09452470e-02,
         6.44161175e-04,  7.60853964e-03, -8.48696659e-03,
         1.48593693e-02, -1.27990707e-03, -1.30235156e-05,
        -1.14656051e-01,  4.16507148e-01, -2.95503492e-05,
        -2.54435429e-07],
       [-2.39334627e-03,  8.81583159e-05, -3.01103655e-05,
        -5.29340774e-08,  6.00060778e-11,  5.93669402e-06,
         3.59784193e-05,  7.71346552e-06, -4.54508609e-06,
         1.29432178e-05,  2.06503373e-07,  5.39816612e-09,
         2.30745412e-05, -5.44146853e-06,  1.28518298e-09,
         1.57422765e-10],
       [ 1.07464267e-02, -3.01103655e-05,  2.55086310e-04,
        -1.11078684e-07, -1.63337105e-11, -5.49987393e-05,
         1.42826726e-05, -7.40223074e-06, -1.53042584e-05,
        -9.95416517e-06, -1.93798658e-06, -3.93715476e-08,
        -3.05162791e-05,  4.49714792e-05,  1.38443414e-08,
         1.73094041e-10],
       [-6.18082466e-06, -5.29340774e-08, -1.11078684e-07,
         2.74910000e-10, -2.12866091e-13,  6.47326381e-09,
        -4.78092855e-08, -1.09542922e-08, -1.50303266e-09,
        -6.46739807e-08,  9.78760122e-10, -1.03852908e-12,
         1.85406755e-08, -3.20914397e-08, -1.05543103e-10,
        -3.15693662e-13],
       [-1.68980105e-07,  6.00060778e-11, -1.63337105e-11,
        -2.12866091e-13,  5.66485873e-14,  3.44839791e-11,
         3.29505709e-10, -7.31488913e-11,  5.97016496e-11,
        -6.25474515e-11,  3.80352681e-12,  6.09221273e-14,
         4.74436597e-10, -1.13603829e-09,  2.49143411e-13,
        -5.97506671e-14],
       [ 1.09452470e-02,  5.93669402e-06, -5.49987393e-05,
         6.47326381e-09,  3.44839791e-11,  2.54516448e-04,
        -2.78636109e-05,  7.77355426e-06,  2.11841188e-05,
        -2.83580079e-05, -1.29356776e-06, -1.51957406e-08,
        -4.76393426e-05,  5.17090803e-05,  1.71155389e-08,
         1.75766593e-10],
       [ 6.44161176e-04,  3.59784193e-05,  1.42826726e-05,
        -4.78092855e-08,  3.29505709e-10, -2.78636109e-05,
         7.42926698e-03, -3.36810404e-04, -9.31664284e-06,
         1.69992449e-05, -4.33039047e-07, -8.72666604e-08,
         7.47952641e-05,  2.85637921e-05,  3.23508476e-08,
        -3.76664727e-10],
       [ 7.60853964e-03,  7.71346552e-06, -7.40223074e-06,
        -1.09542922e-08, -7.31488913e-11,  7.77355426e-06,
        -3.36810404e-04,  1.09009432e-04, -2.34393937e-06,
        -6.41999087e-06,  3.48710697e-07, -5.84742828e-09,
         2.88300906e-05,  7.84300731e-05, -2.26957354e-08,
        -8.84559191e-12],
       [-8.48696659e-03, -4.54508609e-06, -1.53042584e-05,
        -1.50303266e-09,  5.97016496e-11,  2.11841188e-05,
        -9.31664284e-06, -2.34393937e-06,  1.33980389e-04,
        -2.37169293e-06,  1.29506476e-06,  3.58133652e-08,
         4.21075780e-05, -2.85876995e-05,  8.03799722e-09,
        -6.41743991e-11],
       [ 1.48593693e-02,  1.29432178e-05, -9.95416517e-06,
        -6.46739807e-08, -6.25474515e-11, -2.83580079e-05,
         1.69992449e-05, -6.41999087e-06, -2.37169293e-06,
         1.11906457e-04, -8.66891651e-07, -6.94658196e-09,
        -7.96294889e-05,  8.13608980e-05, -5.68187296e-08,
         9.54697577e-11],
       [-1.27990707e-03,  2.06503373e-07, -1.93798658e-06,
         9.78760122e-10,  3.80352681e-12, -1.29356776e-06,
        -4.33039047e-07,  3.48710697e-07,  1.29506476e-06,
        -8.66891651e-07,  1.28204820e-07,  2.07088915e-09,
         4.04237264e-06, -6.87291039e-06,  1.14754889e-10,
        -1.78236849e-12],
       [-1.30235156e-05,  5.39816612e-09, -3.93715476e-08,
        -1.03852908e-12,  6.09221273e-14, -1.51957406e-08,
        -8.72666604e-08, -5.84742828e-09,  3.58133652e-08,
        -6.94658196e-09,  2.07088915e-09,  3.29696808e-10,
         4.29241120e-08, -5.61594281e-08,  1.62658975e-11,
        -9.14339308e-14],
       [-1.14656051e-01,  2.30745412e-05, -3.05162791e-05,
         1.85406755e-08,  4.74436597e-10, -4.76393426e-05,
         7.47952641e-05,  2.88300906e-05,  4.21075780e-05,
        -7.96294889e-05,  4.04237264e-06,  4.29241120e-08,
         2.66584808e-03,  1.60503383e-04, -1.10587736e-08,
         4.51983323e-10],
       [ 4.16507148e-01, -5.44146853e-06,  4.49714792e-05,
        -3.20914397e-08, -1.13603829e-09,  5.17090803e-05,
         2.85637921e-05,  7.84300731e-05, -2.85876995e-05,
         8.13608980e-05, -6.87291039e-06, -5.61594281e-08,
         1.60503383e-04,  3.36045039e-03, -2.44298691e-07,
        -1.92529446e-09],
       [-2.95503492e-05,  1.28518298e-09,  1.38443414e-08,
        -1.05543103e-10,  2.49143411e-13,  1.71155389e-08,
         3.23508476e-08, -2.26957354e-08,  8.03799722e-09,
        -5.68187296e-08,  1.14754889e-10,  1.62658975e-11,
        -1.10587736e-08, -2.44298691e-07,  2.84634989e-10,
        -3.20729225e-13],
       [-2.54435429e-07,  1.57422765e-10,  1.73094041e-10,
        -3.15693662e-13, -5.97506671e-14,  1.75766593e-10,
        -3.76664727e-10, -8.84559191e-12, -6.41743991e-11,
         9.54697577e-11, -1.78236849e-12, -9.14339308e-14,
         4.51983323e-10, -1.92529446e-09, -3.20729225e-13,
         1.32505231e-13]])

In [37]:
XT_Y = np.matmul(np.matrix.transpose(X), Y)
XT_Y

array([[ 1.16729250e+10],
       [ 4.16230285e+10],
       [ 2.78943857e+10],
       [ 2.93944075e+13],
       [ 2.05809089e+14],
       [ 1.85431805e+10],
       [ 2.70885792e+08],
       [ 5.15064376e+09],
       [ 3.99857591e+10],
       [ 9.56029351e+10],
       [ 2.30199830e+13],
       [ 1.38817393e+12],
       [ 5.55502450e+11],
       [-1.42656948e+12],
       [ 2.63722487e+13],
       [ 1.66906659e+14]])

In [38]:
betas = np.matmul(XT_X_inv, XT_Y)
betas

array([[-3.41851323e+07],
       [-3.42672956e+04],
       [ 3.83782497e+04],
       [ 1.68054502e+02],
       [ 1.38709117e-01],
       [ 1.27012472e+04],
       [ 5.92651278e+05],
       [ 4.67442013e+04],
       [ 2.96452742e+04],
       [ 9.95615727e+04],
       [-2.46283274e+03],
       [ 2.13028367e+01],
       [ 5.51257600e+05],
       [-9.89055453e+04],
       [ 3.12213840e+01],
       [-3.84180679e-01]])

In [39]:
Y_pred = np.matmul(X, betas)
Y_pred

array([[255733.53786831],
       [734438.79537263],
       [341077.85083077],
       ...,
       [174056.77342781],
       [373127.08635928],
       [176565.94002944]], shape=(21613, 1))

In [40]:
Resid = Y - Y_pred
Resid

array([[ -33833.53786831],
       [-196438.79537263],
       [-161077.85083077],
       ...,
       [ 228044.22657219],
       [  26872.91364072],
       [ 148434.05997056]], shape=(21613, 1))

In [41]:
RSS = float(np.matmul(np.matrix.transpose(Resid), Resid))
RSS

889539015443041.2

In [42]:
TSS = float(np.matmul(np.matrix.transpose(Y), Y) - len(Y) * (Y.mean()**2))
TSS

2912916761921300.0

In [43]:
R_cuad = float(1 - RSS / TSS)
R_cuad

0.6946225765626342

In [44]:
RSqAj = float(1 - (RSS / (X.shape[0] - X.shape[1])) / (TSS / (X.shape[0] - 1)))
RSqAj

0.694410479449537

In [45]:
s_cuad = RSS / (len(Y) - X.shape[1])
s_cuad

41188082393.06576

In [46]:
import math
s = math.sqrt(s_cuad)
s

202948.47226097996

In [47]:
result_t = []
for i in range(0, X.shape[1]):
    t = float(betas[i] / (s * math.sqrt(XT_X_inv[i][i])))
    result_t.append(t)
result_t

[-21.95920991715802,
 -17.983010654720605,
 11.84011176898266,
 49.942363928240965,
 2.871604845360063,
 3.9228585973805283,
 33.87977018934561,
 22.060224061018427,
 12.619701097033461,
 46.37440913633092,
 -33.89198110510034,
 5.780884355199745,
 52.60791685282996,
 -8.406904440911074,
 9.118475200015856,
 -5.200357745838463]

In [48]:
import scipy.stats
grados_libertad = len(Y) - X.shape[1]
t_critico = float(abs(scipy.stats.t.ppf(q=0.025, df=grados_libertad)))
t_critico

1.9600738332192764

In [51]:
#Criterio 1
for i in range(0, X.shape[1]):
    if abs(result_t[i]) > t_critico:
        print(f"Beta {i} ({nombres[i]}) SÍ es significativa")
    else:
        print(f"Beta {i} ({nombres[i]}) NO es significativa")

Beta 0 (const) SÍ es significativa
Beta 1 (bedrooms) SÍ es significativa
Beta 2 (bathrooms) SÍ es significativa
Beta 3 (sqft_living) SÍ es significativa
Beta 4 (sqft_lot) SÍ es significativa
Beta 5 (floors) SÍ es significativa
Beta 6 (waterfront) SÍ es significativa
Beta 7 (view) SÍ es significativa
Beta 8 (condition) SÍ es significativa
Beta 9 (grade) SÍ es significativa
Beta 10 (yr_built) SÍ es significativa
Beta 11 (yr_renovated) SÍ es significativa
Beta 12 (lat) SÍ es significativa
Beta 13 (long) SÍ es significativa
Beta 14 (sqft_living15) SÍ es significativa
Beta 15 (sqft_lot15) SÍ es significativa

In [52]:
# Criterio 2
for i in range(0, X.shape[1]):
    p = scipy.stats.t.sf(abs(result_t[i]), df=grados_libertad) * 2
    print(f"Valor p de Beta {i} ({nombres[i]}) = {p:.4e}")

Valor p de Beta 0 (const) = 1.0143e-105
Valor p de Beta 1 (bedrooms) = 8.8424e-72
Valor p de Beta 2 (bathrooms) = 3.0467e-32
Valor p de Beta 3 (sqft_living) = 0.0000e+00
Valor p de Beta 4 (sqft_lot) = 4.0879e-03
Valor p de Beta 5 (floors) = 8.7775e-05
Valor p de Beta 6 (waterfront) = 3.3939e-245
Valor p de Beta 7 (view) = 1.1477e-106
Valor p de Beta 8 (condition) = 2.2105e-36
Valor p de Beta 9 (grade) = 0.0000e+00
Valor p de Beta 10 (yr_built) = 2.2904e-245
Valor p de Beta 11 (yr_renovated) = 7.5332e-09
Valor p de Beta 12 (lat) = 0.0000e+00
Valor p de Beta 13 (long) = 4.4670e-17
Valor p de Beta 14 (sqft_living15) = 8.2677e-20
Valor p de Beta 15 (sqft_lot15) = 2.0072e-07

In [53]:
# Criterio 3
for i in range(0, X.shape[1]):
    li = float(betas[i]) - t_critico * s * math.sqrt(XT_X_inv[i][i])
    ls = float(betas[i]) + t_critico * s * math.sqrt(XT_X_inv[i][i])
    print(f"El valor de Beta {i} ({nombres[i]}) está entre {li:.4f} y {ls:.4f}")

El valor de Beta 0 (const) está entre -37236489.0174 y -31133775.5310
El valor de Beta 1 (bedrooms) está entre -38002.2892 y -30532.3020
El valor de Beta 2 (bathrooms) está entre 32024.9141 y 44731.5852
El valor de Beta 3 (sqft_living) está entre 161.4589 y 174.6501
El valor de Beta 4 (sqft_lot) está entre 0.0440 y 0.2334
El valor de Beta 5 (floors) está entre 6355.0122 y 19047.4821
El valor de Beta 6 (waterfront) está entre 558364.1425 y 626938.4130
El valor de Beta 7 (view) está entre 42590.9304 y 50897.4722
El valor de Beta 8 (condition) está entre 25040.8129 y 34249.7356
El valor de Beta 9 (grade) está entre 95353.4752 y 103769.6702
El valor de Beta 10 (yr_built) está entre -2605.2657 y -2320.3998
El valor de Beta 11 (yr_renovated) está entre 14.0799 y 28.5258
El valor de Beta 12 (lat) está entre 530718.7595 y 571796.4399
El valor de Beta 13 (long) está entre -121965.4210 y -75845.6696
El valor de Beta 14 (sqft_living15) está entre 24.5102 y 37.9326
El valor de Beta 15 (sqft_lot15) está entre -0.5290 y -0.2394

In [54]:
import statsmodels.api as sm
regressor = sm.OLS(Y, X).fit()
print(regressor.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.695
Model:                            OLS   Adj. R-squared:                  0.694
Method:                 Least Squares   F-statistic:                     3275.
Date:                Thu, 08 Oct 2026   Prob (F-statistic):               0.00
Time:                        14:30:03   Log-Likelihood:            -2.9479e+05
No. Observations:               21613   AIC:                         5.896e+05
Df Residuals:                   21597   BIC:                         5.897e+05
Df Model:                          15
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3.419e+07   1.56e+06    -21.959      0.000   -3.72e+07   -3.11e+07
x1         -3.427e+04   1905.537    -17.983      0.000    -3.8e+04   -3.05e+04
x2          3.838e+04   3241.376     11.840      0.000     3.2e+04    4.47e+04
x3           168.0545      3.365     49.942      0.000     161.459     174.650
x4             0.1387      0.048      2.872      0.004       0.044       0.233
x5           1.27e+04   3237.753      3.923      0.000    6355.012     1.9e+04
x6          5.927e+05   1.75e+04     33.880      0.000    5.58e+05    6.27e+05
x7          4.674e+04   2118.936     22.060      0.000    4.26e+04    5.09e+04
x8          2.965e+04   2349.126     12.620      0.000     2.5e+04    3.42e+04
x9          9.956e+04   2146.908     46.374      0.000    9.54e+04    1.04e+05
x10        -2462.8327     72.667    -33.892      0.000   -2605.266   -2320.400
x11           21.3028      3.685      5.781      0.000      14.080      28.526
x12         5.513e+05   1.05e+04     52.608      0.000    5.31e+05    5.72e+05
x13        -9.891e+04   1.18e+04     -8.407      0.000   -1.22e+05   -7.58e+04
x14           31.2214      3.424      9.118      0.000      24.510      37.933
x15           -0.3842      0.074     -5.200      0.000      -0.529      -0.239
==============================================================================
Omnibus:                    18696.032   Durbin-Watson:                   1.991
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1947767.833
Skew:                           3.661   Prob(JB):                         0.00
Kurtosis:                      48.927   Cond. No.                     5.71e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.71e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

In [55]:
data = pd.DataFrame(X)
data2 = data.iloc[:, 1:]  # sin intercepto
data2.columns = nombres[1:]
data2.corr()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15
bedrooms,1.000000,0.515884,0.576671,0.031703,0.175429,-0.006582,0.079532,0.028472,0.356967,0.154178,0.018841,-0.008931,0.129473,0.391638,0.029244
bathrooms,0.515884,1.000000,0.754665,0.087740,0.500653,0.063744,0.187737,-0.124982,0.664983,0.506019,0.050739,0.024573,0.223042,0.568634,0.087175
sqft_living,0.576671,0.754665,1.000000,0.172826,0.353949,0.103818,0.284611,-0.058753,0.762704,0.318049,0.055363,0.052529,0.240223,0.756420,0.183286
sqft_lot,0.031703,0.087740,0.172826,1.000000,-0.005201,0.021604,0.074710,-0.008958,0.113621,0.053080,0.007644,-0.085683,0.229521,0.144608,0.718557
floors,0.175429,0.500653,0.353949,-0.005201,1.000000,0.023698,0.029444,-0.263768,0.458183,0.489319,0.006338,0.049614,0.125419,0.279885,-0.011269
waterfront,-0.006582,0.063744,0.103818,0.021604,0.023698,1.000000,0.401857,0.016653,0.082775,-0.026161,0.092885,-0.014274,-0.041910,0.086463,0.030703
view,0.079532,0.187737,0.284611,0.074710,0.029444,0.401857,1.000000,0.045990,0.251321,-0.053440,0.103917,0.006157,-0.078400,0.280439,0.072575
condition,0.028472,-0.124982,-0.058753,-0.008958,-0.263768,0.016653,0.045990,1.000000,-0.144674,-0.361417,-0.060618,-0.014941,-0.106500,-0.092824,-0.003406
grade,0.356967,0.664983,0.762704,0.113621,0.458183,0.082775,0.251321,-0.144674,1.000000,0.446963,0.014414,0.114084,0.198372,0.713202,0.119248
yr_built,0.154178,0.506019,0.318049,0.053080,0.489319,-0.026161,-0.053440,-0.361417,0.446963,1.000000,-0.224874,-0.148122,0.409356,0.326229,0.070958
yr_renovated,0.018841,0.050739,0.055363,0.007644,0.006338,0.092885,0.103917,-0.060618,0.014414,-0.224874,1.000000,0.029398,-0.068372,-0.002673,0.007854
lat,-0.008931,0.024573,0.052529,-0.085683,0.049614,-0.014274,0.006157,-0.014941,0.114084,-0.148122,0.029398,1.000000,-0.135512,0.048858,-0.086419
long,0.129473,0.223042,0.240223,0.229521,0.125419,-0.041910,-0.078400,-0.106500,0.198372,0.409356,-0.068372,-0.135512,1.000000,0.334605,0.254451
sqft_living15,0.391638,0.568634,0.756420,0.144608,0.279885,0.086463,0.280439,-0.092824,0.713202,0.326229,-0.002673,0.048858,0.334605,1.000000,0.183192
sqft_lot15,0.029244,0.087175,0.183286,0.718557,-0.011269,0.030703,0.072575,-0.003406,0.119248,0.070958,0.007854,-0.086419,0.254451,0.183192,1.000000

In [56]:
#Pares con correlacion alta
corr_matrix = data2.corr().abs()
pares_altos = []
for i in range(len(corr_matrix.columns)):
    for j in range(i+1, len(corr_matrix.columns)):
        if corr_matrix.iloc[i, j] > 0.75:
            pares_altos.append((corr_matrix.columns[i],
                                corr_matrix.columns[j],
                                corr_matrix.iloc[i, j]))
for a, b, r in sorted(pares_altos, key=lambda x: -x[2]):
    print(f"{a:<20} vs {b:<20} → r = {r:.4f}")

sqft_living          vs grade                → r = 0.7627
sqft_living          vs sqft_living15        → r = 0.7564
bathrooms            vs sqft_living          → r = 0.7547

In [58]:
from scipy.stats import jarque_bera
jb_stat, jb_p = jarque_bera(Resid.flatten())
print(f"Jarque-Bera: estadístico = {jb_stat:.4f}, p-valor = {jb_p:.4e}")
if jb_p < 0.05:
    print("Residuos NO normales. Las pruebas t y F pueden no ser válidas.")
else:
    print("Residuos normales. Las pruebas t y F son válidas.")

Jarque-Bera: estadístico = 1947767.8327, p-valor = 0.0000e+00
Residuos NO normales. Las pruebas t y F pueden no ser válidas.

In [67]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm

X_df = pd.DataFrame(X[:, 1:], columns=nombres[1:])
vif_data = pd.DataFrame()
vif_data["Variable"] = X_df.columns
vif_data["VIF"] = [variance_inflation_factor(X_df.values, i) 
                   for i in range(X_df.shape[1])]
vif_data = vif_data.sort_values("VIF", ascending=False)
print(vif_data)

         Variable            VIF
12           long  133041.151227
11            lat  119405.672428
9        yr_built    8428.756127
8           grade     140.273617
7       condition      34.567865
2     sqft_living      30.642581
1       bathrooms      27.711164
13  sqft_living15      25.750734
0        bedrooms      23.272223
4          floors      13.776027
14     sqft_lot15       2.580240
3        sqft_lot       2.359496
6            view       1.499179
5      waterfront       1.210969
10   yr_renovated       1.189924

### ENFOQUE 1: StepWise Forward

In [77]:
def stepwise_forward(X, Y, nombres, alfa=0.01):
    n, k_total = X.shape
    incluidas = [0]  # intercepto
    candidatas = list(range(1, k_total))
    
    while True:
        mejor_p = 1.0
        mejor_var = None
        for j in candidatas:
            cols = incluidas + [j]
            X_test = X[:, cols]
            try:
                XT_X = np.matmul(X_test.T, X_test)
                XT_X_inv = np.linalg.inv(XT_X)
                XT_Y = np.matmul(X_test.T, Y)
                betas = np.matmul(XT_X_inv, XT_Y)
                Y_pred = np.matmul(X_test, betas)
                Resid = Y - Y_pred
                RSS = float(np.matmul(Resid.T, Resid))
                gl = n - len(cols)
                s = math.sqrt(RSS / gl)
                idx = len(cols) - 1
                t = float(betas[idx] / (s * math.sqrt(XT_X_inv[idx][idx])))
                p = scipy.stats.t.sf(abs(t), df=gl) * 2
                if p < mejor_p:
                    mejor_p = p
                    mejor_var = j
            except np.linalg.LinAlgError:
                continue
        if mejor_var is not None and mejor_p < alfa:
            incluidas.append(mejor_var)
            candidatas.remove(mejor_var)
        else:
            break
    return incluidas

cols_fwd = stepwise_forward(X, Y, nombres)
nombres_fwd = [nombres[i] for i in cols_fwd]
X_fwd = X[:, cols_fwd]

XT_X_f = np.matmul(X_fwd.T, X_fwd)
XT_X_inv_f = np.linalg.inv(XT_X_f)
XT_Y_f = np.matmul(X_fwd.T, Y)
betas_f = np.matmul(XT_X_inv_f, XT_Y_f)
Y_pred_f = np.matmul(X_fwd, betas_f)
Resid_f = Y - Y_pred_f
RSS_f = float(np.matmul(Resid_f.T, Resid_f))
TSS_f = TSS
R_cuad_f = float(1 - RSS_f / TSS_f)
RSqAj_f = float(1 - (RSS_f / (X_fwd.shape[0] - X_fwd.shape[1])) / (TSS_f / (X_fwd.shape[0] - 1)))
s_cuad_f = RSS_f / (len(Y) - X_fwd.shape[1])
s_f = math.sqrt(s_cuad_f)

result_t_f = []
for i in range(0, X_fwd.shape[1]):
    t = float(betas_f[i] / (s_f * math.sqrt(XT_X_inv_f[i][i])))
    result_t_f.append(t)

gl_f = len(Y) - X_fwd.shape[1]

print(f"N° parámetros: {X_fwd.shape[1]}")
print(f"R²        = {R_cuad_f:.6f}")
print(f"R² aj.    = {RSqAj_f:.6f}")
print(f"RSS       = {RSS_f:.4e}")
print(f"s         = {s_f:.4e}")
print()
for i in range(0, X_fwd.shape[1]):
    p = scipy.stats.t.sf(abs(result_t_f[i]), df=gl_f) * 2
    sig = "SÍ" if p < 0.05 else "NO"
    print(f"Beta {i} ({nombres_fwd[i]}): t={result_t_f[i]:.4f}, p={p:.4e} → {sig} significativa")

N° parámetros: 16
R²        = 0.694623
R² aj.    = 0.694410
RSS       = 8.8954e+14
s         = 2.0295e+05

Beta 0 (const): t=-21.9592, p=1.0143e-105 → SÍ significativa
Beta 1 (bedrooms): t=-17.9830, p=8.8424e-72 → SÍ significativa
Beta 2 (bathrooms): t=11.8401, p=3.0467e-32 → SÍ significativa
Beta 3 (sqft_living): t=49.9424, p=0.0000e+00 → SÍ significativa
Beta 4 (waterfront): t=33.8798, p=3.3939e-245 → SÍ significativa
Beta 5 (grade): t=46.3744, p=0.0000e+00 → SÍ significativa
Beta 6 (yr_built): t=-33.8920, p=2.2904e-245 → SÍ significativa
Beta 7 (lat): t=52.6079, p=0.0000e+00 → SÍ significativa
Beta 8 (view): t=22.0602, p=1.1477e-106 → SÍ significativa
Beta 9 (condition): t=12.6197, p=2.2105e-36 → SÍ significativa
Beta 10 (long): t=-8.4069, p=4.4670e-17 → SÍ significativa
Beta 11 (sqft_living15): t=9.1185, p=8.2677e-20 → SÍ significativa
Beta 12 (yr_renovated): t=5.7809, p=7.5332e-09 → SÍ significativa
Beta 13 (sqft_lot15): t=-5.2004, p=2.0072e-07 → SÍ significativa
Beta 14 (floors): t=3.9229, p=8.7775e-05 → SÍ significativa
Beta 15 (sqft_lot): t=2.8716, p=4.0879e-03 → SÍ significativa

### Enfoque 2: StepWise Backward

In [78]:
def stepwise_backward(X, Y, nombres, alfa=0.01):
    n, k = X.shape
    incluidas = list(range(k))
    
    while len(incluidas) > 1:
        cols = incluidas
        X_test = X[:, cols]
        try:
            XT_X = np.matmul(X_test.T, X_test)
            XT_X_inv = np.linalg.inv(XT_X)
            XT_Y = np.matmul(X_test.T, Y)
            betas = np.matmul(XT_X_inv, XT_Y)
            Y_pred = np.matmul(X_test, betas)
            Resid = Y - Y_pred
            RSS = float(np.matmul(Resid.T, Resid))
            gl = n - len(cols)
            s = math.sqrt(RSS / gl)
            
            pvals = []
            for i in range(len(cols)):
                t = float(betas[i] / (s * math.sqrt(XT_X_inv[i][i])))
                p = scipy.stats.t.sf(abs(t), df=gl) * 2
                pvals.append(p)
            
            pvals_sin_int = pvals[1:]
            if len(pvals_sin_int) == 0:
                break
            max_p = max(pvals_sin_int)
            idx_max = pvals_sin_int.index(max_p) + 1
            
            if max_p > alfa:
                incluidas.pop(idx_max)
            else:
                break
        except np.linalg.LinAlgError:
            break
    return incluidas

cols_bwd = stepwise_backward(X, Y, nombres)
nombres_bwd = [nombres[i] for i in cols_bwd]
X_bwd = X[:, cols_bwd]

XT_X_b = np.matmul(X_bwd.T, X_bwd)
XT_X_inv_b = np.linalg.inv(XT_X_b)
XT_Y_b = np.matmul(X_bwd.T, Y)
betas_b = np.matmul(XT_X_inv_b, XT_Y_b)
Y_pred_b = np.matmul(X_bwd, betas_b)
Resid_b = Y - Y_pred_b
RSS_b = float(np.matmul(Resid_b.T, Resid_b))
TSS_b = TSS
R_cuad_b = float(1 - RSS_b / TSS_b)
RSqAj_b = float(1 - (RSS_b / (X_bwd.shape[0] - X_bwd.shape[1])) / (TSS_b / (X_bwd.shape[0] - 1)))
s_cuad_b = RSS_b / (len(Y) - X_bwd.shape[1])
s_b = math.sqrt(s_cuad_b)

result_t_b = []
for i in range(0, X_bwd.shape[1]):
    t = float(betas_b[i] / (s_b * math.sqrt(XT_X_inv_b[i][i])))
    result_t_b.append(t)

gl_b = len(Y) - X_bwd.shape[1]

print(f"N° parámetros: {X_bwd.shape[1]}")
print(f"R²        = {R_cuad_b:.6f}")
print(f"R² aj.    = {RSqAj_b:.6f}")
print(f"RSS       = {RSS_b:.4e}")
print(f"s         = {s_b:.4e}")
print()
for i in range(0, X_bwd.shape[1]):
    p = scipy.stats.t.sf(abs(result_t_b[i]), df=gl_b) * 2
    sig = "SÍ" if p < 0.05 else "NO"
    print(f"Beta {i} ({nombres_bwd[i]}): t={result_t_b[i]:.4f}, p={p:.4e} → {sig} significativa")

N° parámetros: 16
R²        = 0.694623
R² aj.    = 0.694410
RSS       = 8.8954e+14
s         = 2.0295e+05

Beta 0 (const): t=-21.9592, p=1.0143e-105 → SÍ significativa
Beta 1 (bedrooms): t=-17.9830, p=8.8424e-72 → SÍ significativa
Beta 2 (bathrooms): t=11.8401, p=3.0467e-32 → SÍ significativa
Beta 3 (sqft_living): t=49.9424, p=0.0000e+00 → SÍ significativa
Beta 4 (sqft_lot): t=2.8716, p=4.0879e-03 → SÍ significativa
Beta 5 (floors): t=3.9229, p=8.7775e-05 → SÍ significativa
Beta 6 (waterfront): t=33.8798, p=3.3939e-245 → SÍ significativa
Beta 7 (view): t=22.0602, p=1.1477e-106 → SÍ significativa
Beta 8 (condition): t=12.6197, p=2.2105e-36 → SÍ significativa
Beta 9 (grade): t=46.3744, p=0.0000e+00 → SÍ significativa
Beta 10 (yr_built): t=-33.8920, p=2.2904e-245 → SÍ significativa
Beta 11 (yr_renovated): t=5.7809, p=7.5332e-09 → SÍ significativa
Beta 12 (lat): t=52.6079, p=0.0000e+00 → SÍ significativa
Beta 13 (long): t=-8.4069, p=4.4670e-17 → SÍ significativa
Beta 14 (sqft_living15): t=9.1185, p=8.2677e-20 → SÍ significativa
Beta 15 (sqft_lot15): t=-5.2004, p=2.0072e-07 → SÍ significativa

In [79]:
### Enfoque 3: StepWise Bidireccional

In [80]:
def stepwise_bidireccional(X, Y, nombres, alfa=0.01):
    n, k_total = X.shape
    incluidas = [0]
    candidatas = list(range(1, k_total))
    
    while True:
        cambio = False
        
        # Forward
        if candidatas:
            mejor_p = 1.0
            mejor_var = None
            for j in candidatas:
                cols = incluidas + [j]
                X_test = X[:, cols]
                try:
                    XT_X = np.matmul(X_test.T, X_test)
                    XT_X_inv = np.linalg.inv(XT_X)
                    XT_Y = np.matmul(X_test.T, Y)
                    betas = np.matmul(XT_X_inv, XT_Y)
                    Y_pred = np.matmul(X_test, betas)
                    Resid = Y - Y_pred
                    RSS = float(np.matmul(Resid.T, Resid))
                    gl = n - len(cols)
                    s = math.sqrt(RSS / gl)
                    idx = len(cols) - 1
                    t = float(betas[idx] / (s * math.sqrt(XT_X_inv[idx][idx])))
                    p = scipy.stats.t.sf(abs(t), df=gl) * 2
                    if p < mejor_p:
                        mejor_p = p
                        mejor_var = j
                except np.linalg.LinAlgError:
                    continue
            if mejor_var is not None and mejor_p < alfa:
                incluidas.append(mejor_var)
                candidatas.remove(mejor_var)
                cambio = True

        if len(incluidas) > 1:
            cols = incluidas
            X_test = X[:, cols]
            XT_X = np.matmul(X_test.T, X_test)
            XT_X_inv = np.linalg.inv(XT_X)
            XT_Y = np.matmul(X_test.T, Y)
            betas = np.matmul(XT_X_inv, XT_Y)
            Y_pred = np.matmul(X_test, betas)
            Resid = Y - Y_pred
            RSS = float(np.matmul(Resid.T, Resid))
            gl = n - len(cols)
            s = math.sqrt(RSS / gl)
            
            pvals = []
            for i in range(len(cols)):
                t = float(betas[i] / (s * math.sqrt(XT_X_inv[i][i])))
                p = scipy.stats.t.sf(abs(t), df=gl) * 2
                pvals.append(p)
            
            pvals_sin_int = pvals[1:]
            if pvals_sin_int:
                max_p = max(pvals_sin_int)
                idx_max = pvals_sin_int.index(max_p) + 1
                if max_p > alfa:
                    var_eliminada = incluidas.pop(idx_max)
                    candidatas.append(var_eliminada)
                    cambio = True
        
        if not cambio:
            break
    return incluidas

cols_bid = stepwise_bidireccional(X, Y, nombres)
nombres_bid = [nombres[i] for i in cols_bid]
X_bid = X[:, cols_bid]

XT_X_bid = np.matmul(X_bid.T, X_bid)
XT_X_inv_bid = np.linalg.inv(XT_X_bid)
XT_Y_bid = np.matmul(X_bid.T, Y)
betas_bid = np.matmul(XT_X_inv_bid, XT_Y_bid)
Y_pred_bid = np.matmul(X_bid, betas_bid)
Resid_bid = Y - Y_pred_bid
RSS_bid = float(np.matmul(Resid_bid.T, Resid_bid))
TSS_bid = TSS
R_cuad_bid = float(1 - RSS_bid / TSS_bid)
RSqAj_bid = float(1 - (RSS_bid / (X_bid.shape[0] - X_bid.shape[1])) / (TSS_bid / (X_bid.shape[0] - 1)))
s_cuad_bid = RSS_bid / (len(Y) - X_bid.shape[1])
s_bid = math.sqrt(s_cuad_bid)

result_t_bid = []
for i in range(0, X_bid.shape[1]):
    t = float(betas_bid[i] / (s_bid * math.sqrt(XT_X_inv_bid[i][i])))
    result_t_bid.append(t)

gl_bid = len(Y) - X_bid.shape[1]

print(f"N° parámetros: {X_bid.shape[1]}")
print(f"R²        = {R_cuad_bid:.6f}")
print(f"R² aj.    = {RSqAj_bid:.6f}")
print(f"RSS       = {RSS_bid:.4e}")
print(f"s         = {s_bid:.4e}")
print()
for i in range(0, X_bid.shape[1]):
    p = scipy.stats.t.sf(abs(result_t_bid[i]), df=gl_bid) * 2
    sig = "SÍ" if p < 0.05 else "NO"
    print(f"Beta {i} ({nombres_bid[i]}): t={result_t_bid[i]:.4f}, p={p:.4e} → {sig} significativa")

N° parámetros: 16
R²        = 0.694623
R² aj.    = 0.694410
RSS       = 8.8954e+14
s         = 2.0295e+05

Beta 0 (const): t=-21.9592, p=1.0143e-105 → SÍ significativa
Beta 1 (bedrooms): t=-17.9830, p=8.8424e-72 → SÍ significativa
Beta 2 (sqft_living): t=49.9424, p=0.0000e+00 → SÍ significativa
Beta 3 (waterfront): t=33.8798, p=3.3939e-245 → SÍ significativa
Beta 4 (grade): t=46.3744, p=0.0000e+00 → SÍ significativa
Beta 5 (yr_built): t=-33.8920, p=2.2904e-245 → SÍ significativa
Beta 6 (lat): t=52.6079, p=0.0000e+00 → SÍ significativa
Beta 7 (view): t=22.0602, p=1.1477e-106 → SÍ significativa
Beta 8 (bathrooms): t=11.8401, p=3.0467e-32 → SÍ significativa
Beta 9 (condition): t=12.6197, p=2.2105e-36 → SÍ significativa
Beta 10 (long): t=-8.4069, p=4.4670e-17 → SÍ significativa
Beta 11 (sqft_living15): t=9.1185, p=8.2677e-20 → SÍ significativa
Beta 12 (yr_renovated): t=5.7809, p=7.5332e-09 → SÍ significativa
Beta 13 (sqft_lot15): t=-5.2004, p=2.0072e-07 → SÍ significativa
Beta 14 (floors): t=3.9229, p=8.7775e-05 → SÍ significativa
Beta 15 (sqft_lot): t=2.8716, p=4.0879e-03 → SÍ significativa

In [81]:
comparacion_stepwise = pd.DataFrame({
    'Enfoque': ['Forward', 'Backward', 'Bidireccional'],
    'N° variables': [len(nombres_fwd), len(nombres_bwd), len(nombres_bid)],
    'R²': [R_cuad_f, R_cuad_b, R_cuad_bid],
    'R² ajustado': [RSqAj_f, RSqAj_b, RSqAj_bid],
    'RSS': [RSS_f, RSS_b, RSS_bid],
    's (error típico)': [s_f, s_b, s_bid],
})
comparacion_stepwise

,Enfoque,N° variables,R²,R² ajustado,RSS,s (error típico)
0,Forward,16,0.694623,0.69441,8.895390e+14,202948.472261
1,Backward,16,0.694623,0.69441,8.895390e+14,202948.472261
2,Bidireccional,16,0.694623,0.69441,8.895390e+14,202948.472261